#!/bin/sh
# deploy script
NODE_ENV=test
tmp_dir=~/tmp/test.example.com

mkdir -p "$tmp_dir"
git --work-tree="$tmp_dir" checkout -f

# change to tmp directory
cd "$tmp_dir"

# install packages
npm install

# deploy app
NODE_ENV=$NODE_ENV grunt deploy

# cleanup
rm -rf "$tmp_dir"

# restart app
# /etc/init.d/node-app restart