#!/bin/sh
# build and deploy

tmpDir=~/tmp/example.com
www=~/www/example.com
url=http://example.com

mkdir -p "$tmpDir"
git --work-tree="$tmpDir" checkout -f

# change to tmp directory
cd "$tmpDir"

# update packages
npm update
npm install

# replace with
# grunt deploy


# copy files to www directory
rsync -avz --delete --progress . "$www"

# cleanup
rm -rf "$tmpDir"
